routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::match(['get', 'post'], '/register', function () {
    return redirect('/login');
})->name('register');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::resource('categories', 'CategoryController');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::resource('books', 'BookController');
Route::get('ajax/categories/search', 'CategoryController@ajaxSearch');

Route::resource('orders', 'OrderController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    public function categories(){
        return $this->belongsToMany('App\Category');
    }

    public function order(){
        return $this->belongsToMany('App\Order');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BookController extends Controller
{
    public function __construct(){
        $this->middleware(function($request, $next){
            if (Gate::allows('manage-books')) return $next($request);
            abort(403, 'Anda tidak memiliki cukup hak akses');
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->get('status');
        $keyword = $request->get('keyword') ? $request->get('keyword') : '';

        if ($status) {
            $books = \App\Book::with('categories')->where('title', 'LIKE', "%$keyword%")->where('status', strtoupper($status))->paginate(10);
        } else {
            $books = \App\Book::with('categories')->where('title', 'lIKE', "%$keyword%")->paginate(10);
        }

        return view('books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ]);

        $book = new \App\Book;
        $book->title = $request->get('title');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->price = $request->get('price');
        $book->stock = $request->get('stock');

        $book->status = $request->get('save_action');

        $cover = $request->file('cover');
        if ($cover) {
            $cover_path = $cover->store('book-covers', 'public');
            $book->cover = $cover_path;
        }

        $book->slug = \Str::slug($request->get('title'));
        $book->created_by = \Auth::user()->id;

        $book->save();
        $book->categories()->attach($request->get('categories'));

        if ($request->get('save_action') == 'PUBLISH') {
            return redirect()->route('books.create')->with('status', "Book successfully saved and published");
        } else {
            return redirect()->route('books.create')->with('status', 'Book saved as draft');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = \App\Book::findorFail($id);

        return view('books.edit', ['book' => $book]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = \App\Book::findOrFail($id);

        $request->validate([
            "title" => 'required|min:5|max:200',
            'slug' => [
                "required",
                Rule::unique('books')->ignore($book->slug, 'slug')
            ],
            'description' => 'required|min:20|max:1000',
            'author' => 'required|min:3|max|100',
            'publisher' => 'required|min:3|max:200',
            'price' => 'required|digits_between:0,10',
            'stock' => 'required|digits_between:0,10'
        ]);

        $book->title = $request->get('title');
        $book->slug = $request->get('slug');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->stock = $request->get('stock');
        $book->price = $request->get('price');

        $new_cover = $request->file('cover');
        if ($new_cover) {
            if ($book->cover && file_exists(storage_path('app/public/'.$book->cover))) {
                \Storage::delete('public/'.$book->cover);
            }
            $new_cover_path = $new_cover->store('book-covers', 'public');
            $book->cover = $new_cover_path;
        }

        $book->updated_by = \Auth::user()->id;
        $book->status = $request->get('status');
        $book->save();
        $book->categories()->sync($request->get('categories'));

        return redirect()->route('books.edit', [$book->id])->with('status', 'Book successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = \App\Book::findOrFail($id);
        $book->delete();

        return redirect()->route('books.index')->with('status', 'Book moved to trash');
    }

    public function trash(){
        $books = \App\Book::onlyTrashed()->paginate(10);

        return view('books.trash', ['books' => $books]);
    }

    public function restore($id){
        $book = \App\Book::withTrashed()->findOrFail($id);

        if ($book->trashed()) {
            $book->restore();
            return redirect()->route('books.trash')->with('status', 'Book successfully restored');
        } else {
            return redirect()->route('books.trash')->with('status', 'Book is not in trash');
        }
    }

    public function deletePermanent($id){
        $book = \App\Book::withTrashed()->findOrFail($id);

        if (!$book->trashed()) {
            return redirect()->route('books.trash')->trash('status', 'Book is not in trash!')->with('status_type', 'alert');
        } else {
            $book->categories()->detach();
            $book->forceDelete();

            return redirect()->route('books.trash')->with('status', 'Book permanently deleted');
        }
    }
}

resources/views/books/create.blade.php
@extends('layouts.global')
@section('title', 'Create Book')

@section('content')
    <div class="row">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <form action="{{ route('books.store') }}" enctype="multipart/form-data" method="post" class="shadow-sm p-3 bg-white">
                @csrf
                <label for="title">Title</label> <br>
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Book title" value="{{ old('title') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('title' )}}
                </div>
                <br>
                <label for="cover">Cover</label>
                <input type="file" class="form-control @error('cover') is-invalid @enderror" name="cover" value="{{ old('cover') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('cover') }}
                </div>
                <br>
                <label for="description">Description</label><br>
                <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror" placeholder="Give a description about this book">{{ old('description') }}</textarea>
                <div class="invalid-feedback">
                    {{ $errors->first('description') }}
                </div>
                <br>
                <label for="categories">categories</label>
                <select name="categories[]" multiple id="categories" class="form-control"></select>
                <br><br>
                <label for="stock">Stock</label><br>
                <input type="number" class="form-control @error('stock') is-invalid @enderror" id="stock" name="stock" min=0 value="{{ old('stock') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('stock') }}
                </div>
                <br>
                <label for="author">Author</label><br>
                <input type="text" class="form-control @error('author') is-invalid @enderror" name="author" id="author" placeholder="Book author" value="{{ old('author') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('author') }}
                </div>
                <br>
                <label for="publisher">Publisher</label> <br>
                <input type="text" class="form-control @error('publisher') is-invalid @enderror" id="publisher" name="publisher" placeholder="Book publisher" value="{{ old('publisher') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('publisher') }}
                </div>
                <br>
                <label for="Price">Price</label> <br>
                <input type="number" class="form-control @error('price') is-invalid @enderror" name="price" id="price" placeholder="Book price" value="{{ old('price') }}">
                <div class="invalid-feedback">
                    {{ $errors->first('price') }}
                </div>
                <br>
                <button class="btn btn-primary" name="save_action" value="PUBLISH">Publish</button>
                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
            </form>
        </div>
    </div>
@endsection

@section('footer-script')
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script>
        $('#categories').select2({
            ajax: {
                url: '{{ url('ajax/categories/search') }}',
                processResults: function(data){
                    return {
                        results : data.map(function(item){
                            return {id: item.id, text: item.name}
                        })
                    }
                }
            }
        })
    </script>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.global')
@section('title', 'Edit Book')

@section('content')
    <div class="row">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <form action="{{ route('books.update', [$book->id]) }}" enctype="multipart/form-data" method="post" class="shadow-sm p-3 bg-white">
                @csrf
                @method('put')
                <label for="title">Title</label> <br>
                <input type="text" value="{{ $book->title }}" class="form-control" name="title" placeholder="Book title">
                <br>
                <label for="cover">Cover</label>
                <small class="text-muted">Current Cover</small><br>
                @if ($book->cover)
                    <img src="{{ asset('storage/'.$book->cover) }}" width="96px" alt="">
                @endif
                <br><br>
                <input type="file" class="form-control" name="cover">
                <small class="text-muted">Kosongkan jika tidak ingin mengubah cover</small>
                <br><br>

                <label for="slug">Slug</label>
                <input type="text" name="slug" value="{{ $book->slug }}" placeholder="enter a slug" class="form-control">

                <label for="description">Description</label><br>
                <textarea name="description" id="description" class="form-control" placeholder="Give a description about this book">
                    {{ $book->description }}
                </textarea>
                <br>
                <label for="categories">categories</label>
                <select name="categories[]" multiple id="categories" class="form-control"></select>
                <br><br>
                <label for="stock">Stock</label><br>
                <input type="number" value="{{ $book->stock }}" class="form-control" id="stock" name="stock" min=0 value=0>
                <br>
                <label for="author">Author</label><br>
                <input type="text" value="{{ $book->author }}" class="form-control" name="author" id="author" placeholder="Book author">
                <br>
                <label for="publisher">Publisher</label> <br>
                <input type="text" value="{{ $book->publisher }}" class="form-control" id="publisher" name="publisher" placeholder="Book publisher">
                <br>
                <label for="Price">Price</label> <br>
                <input type="number" value="{{ $book->price }}" class="form-control" name="price" id="price" placeholder="Book price">
                <br>

                <label for="status">Status</label>
                <select name="status" id="status" class="form-control">
                    <option value="PUBLISH" {{ $book->status == 'PUBLISH' ? 'selected' : '' }}>PUBLISH</option>
                    <option value="DRAFT" {{ $book->status == 'DRAFT' ? 'selected' : '' }}>DRAFT</option>
                </select>
                <br>
                <button class="btn btn-primary" name="save_action" value="PUBLISH">Update</button>
            </form>
        </div>
    </div>
@endsection

@section('footer-script')
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script>
        $('#categories').select2({
            ajax: {
                url: '{{ url('ajax/categories/search') }}',
                processResults: function(data){
                    return {
                        results : data.map(function(item){
                            return {id: item.id, text: item.name}
                        })
                    }
                }
            }
        });
        var categories = {!! $book->categories !!}
        categories.forEach(function(cat){
            var option = new Option(cat.name, cat.id, true, true);
            $('#categories').append(option).trigger('change');
        });
    </script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.global')
@section('title', 'Book List')
    
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <form action="{{ route('books.index') }}" method="post">
                        @csrf
                        <div class="input-group">
                            <input type="text" name="keyword" value="{{ Request::get('keyword') }}" placeholder="Filter by title" class="form-control">
                            <div class="input-group-append">
                                <input type="submit" value="Filter" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6">
                    <ul class="nav nav-pills card-header-pills">
                        <li class="nav-item">
                            <a href="{{ route('books.index') }}" class="nav-link {{ Request::get('status') == NULL && Request::path() == 'books' ? 'active' : '' }}">All</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.index', ['status' => 'publish']) }}" class="nav-link {{ Request::get('status') == 'publish' ? 'active' : '' }}"></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.index', ['status' => 'draft']) }}" class="nav-link {{ Request::get('status') == 'draft' ? 'active' : '' }}">Draft</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.trash') }}" class="nav-link {{ Request::path() == 'books/path' ? 'active' : '' }}">Trash</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-12 text-right">
                    <a href="{{ route('books.create') }}" class="btn btn-primary">Create Book</a>
                </div>
            </div>
            @if (session('session'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Cover</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Status</th>
                        <th>Categories</th>
                        <th>Stock</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>
                                @if ($book->cover)
                                    <img src="{{ asset('storage/'.$book->cover) }}" width="96px" alt="">
                                @else
                                    No Cover
                                @endif
                            </td>
                            <td>{{ $book->title }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->status }}</td>
                            <td>
                                <ul class="pl-3">
                                    @foreach ($book->categories as $category)
                                        <li>{{ $category->name }}</li>
                                    @endforeach
                                </ul>
                            </td>
                            <td>{{ $book->stock }}</td>
                            <td>{{ $book->price }}</td>
                            <td>
                                <a href="{{ route('books.edit', [$book->id]) }}" class="btn btn-info btn-sm">Edit</a>
                                <form action="{{ route('books.destroy', [$book->id]) }}" onsubmit="return confirm('Move book to trash?')" method="post" class="d-inline">
                                    @csrf
                                    @method('delete')
                                    <input type="submit" value="Trash" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td>{{ $books->appends(Request::all())->links() }}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

resources/views/books/trash.blade.php
@extends('layouts.global')
@section('title', 'Book List')
    
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <form action="{{ route('books.index') }}" method="post">
                        @csrf
                        <div class="input-group">
                            <input type="text" name="keyword" value="{{ Request::get('keyword') }}" placeholder="Filter by title" class="form-control">
                            <div class="input-group-append">
                                <input type="submit" value="Filter" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6">
                    <ul class="nav nav-pills card-header-pills">
                        <li class="nav-item">
                            <a href="{{ route('books.index') }}" class="nav-link {{ Request::get('status') == NULL && Request::path() == 'books' ? 'active' : '' }}">All</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.index', ['status' => 'publish']) }}" class="nav-link {{ Request::get('status') == 'publish' ? 'active' : '' }}"></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.index', ['status' => 'draft']) }}" class="nav-link {{ Request::get('status') == 'draft' ? 'active' : '' }}">Draft</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('books.trash') }}" class="nav-link {{ Request::path() == 'books/trash' ? 'active' : '' }}">Trash</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-12 text-right">
                    <a href="{{ route('books.create') }}" class="btn btn-primary">Create Book</a>
                </div>
            </div>
            @if (session('session'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Cover</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Status</th>
                        <th>Categories</th>
                        <th>Stock</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>
                                @if ($book->cover)
                                    <img src="{{ asset('storage/'.$book->cover) }}" width="96px" alt="">
                                @else
                                    No Cover
                                @endif
                            </td>
                            <td>{{ $book->title }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->status }}</td>
                            <td>
                                <ul class="pl-3">
                                    @foreach ($book->categories as $category)
                                        <li>{{ $category->name }}</li>
                                    @endforeach
                                </ul>
                            </td>
                            <td>{{ $book->stock }}</td>
                            <td>{{ $book->price }}</td>
                            <td>
                                <a href="{{ route('books.edit', [$book->id]) }}" class="btn btn-info btn-sm">Edit</a>
                                <form action="{{ route('books.restore', [$book->id]) }}" onsubmit="return confirm('Move book to trash?')" method="post" class="d-inline">
                                    @csrf
                                    <input type="submit" value="Restore" class="btn btn-success btn-sm">
                                </form>
                                <form action="{{ route('books.delete-permanent', [$book->id]) }}" onsubmit="return confirm('Delete this book permanently?')" method="post" class="d-inline">
                                    @csrf
                                    @method('delete')
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td>{{ $books->appends(Request::all())->links() }}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection